repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-json
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: debug-statements
      - id: pretty-format-json
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: no-commit-to-branch
        args:
            [
              --branch, develop,
              --branch, main,
              --branch, master
            ]
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    - id: black
      args: [--line-length=80, --skip-string-normalization, --safe]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    - id: add-trailing-comma
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.16.0
    hooks:
    - id: reorder-python-imports
      exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
      args: [--py38-plus, --add-import, 'from __future__ import annotations']
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    - id: flake8
      args: [--max-line-length=90, --extend-ignore=E203]